version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springdrugs
    ports:
      - "3306:3306"
    networks:
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: sudkostik/backendservisi:latest  
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springdrugs
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend-network
      - database-network
      - frontend-network

  frontend:
    image: sudkostik/frontendservisi:0.0.3
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"  
    depends_on:
      - backend
    networks:
      - frontend-network
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  database-network:
    driver: bridge
