# Use an official OpenJDK image as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Add the Maven wrapper and pom.xml to the container
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Add the application source code to the container
COPY src ./src

# Make the Maven wrapper executable and run the package command
RUN chmod +x mvnw && ./mvnw clean package -DskipTests

# Expose the port the application will run on
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "target/SpringSecurityJWT-0.0.1-SNAPSHOT.jar"]
